# HOST image - used to create containers to be managed by master

# use builded ansible_base (defined in ../base/Dockerfile) as a starting point
FROM mcr.microsoft.com/windows:latest

# copy script from local disk to file system inside Docker image
#COPY run.sh /var/run.sh

# adjust file permissions to make run.sh executable
#RUN chmod 755 /var/run.sh

# Sets a command or process that will run each time a container is run from the new image.
CMD ["CMD"]